### ISSUE TITLE
配置文件[system].Listen端口疑问

### ISSUE THREAD

**Issue by Curious-r** [cloudreve/docs#13]
文档中快速开始部分介绍的服务端口均为5212，但在配置文件章的示例文件中[system].Listen对应的端口却是5000，请问这个配置项是否为前述的服务端口呢？以及默认值是多少？

**Comment by xb2016** [comment]
@Curious-r 同一个东西，默认5212

**Comment by Curious-r** [comment]
> @Curious-r 同一个东西，默认5212

好的，感谢回复
